FROM python:3.9-slim

RUN groupadd -r appuser && useradd -r -g appuser appuser

WORKDIR /app
COPY core.py /app/app.py
RUN pip install --no-cache-dir flask

USER appuser

CMD ["python", "/app/app.py"]
