version: "3.8"

services:
  shop-backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - DB_HOST=shop-db
      - DB_PASS=supersecretpassword123

  shop-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: supersecretpassword123
    ports:
      - "5432:5432"
